import Sidebar from "@/components/Sidebar"
import "./globals.css"
import localFont from "next/font/local"

const ubuntu = localFont({
  src: [
    {
      path: "../assets/fonts/Ubuntu-Regular.ttf",
      weight: "400",
      style: "normal",
    },

    {
      path: "../assets/fonts/Ubuntu-Bold.ttf",
      weight: "700",
      style: "normal",
    },

    {
      path: "../assets/fonts/Ubuntu-Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body>
        <main className=" grid h-screen place-content-center bg-gray-50">
          <section className="grid p-5 h-[600px] max-h-full bg-white w-[900px] grid-cols-[280px_1fr] rounded-2xl shadow">
            <Sidebar />
            <article className="px-20 py-10">{children}</article>
          </section>
        </main>
      </body>
    </html>
  )
}
